services:
  minecraft-server:
    build: .
    container_name: minecraft-server
    ports:
      - "25565:25565/tcp" # Minecraft
      - "3333:22/tcp" # SSH (3333 en host → 22 en contenedor)
    volumes:
      - creativo-data:/minecraft/creativo
      - world-data:/minecraft/world
      - discordsrv-config:/minecraft/plugins/DiscordSRV
      - login-config:/minecraft/plugins/nLogin
      - luckperms:/minecraft/plugins/LuckPerms/yaml-storage/users
      - essentials-userdata:/minecraft/plugins/Essentials/userdata
      - jobs-data:/minecraft/plugins/Jobs
    environment:
      - TZ=America/Lima # Ajusta tu zona horaria
    restart: unless-stopped

volumes:
  creativo-data:
  world-data:
  discordsrv-config:
  login-config:
  luckperms:
  essentials-userdata:
  jobs-data:
