services:
  minecraft-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-server
    ports:
      - "0.0.0.0:25565:25565/tcp"
    stdin_open: true # habilita entrada STDIN
    tty: true # habilita pseudo-TTY para logs
    volumes:
      - world-data:/minecraft/world
      - discordsrv-config:/minecraft/plugins/DiscordSRV

volumes:
  world-data:
  discordsrv-config:
