version: "3.8"

services:
  minecraft-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-server
    ports:
      - "0.0.0.0:25565:25565"
    stdin_open: true # habilita entrada STDIN
    tty: true # habilita pseudo-TTY para logs
    restart: unless-stopped
    volumes:
      - world-data:/minecraft/world
# Volumen para persistir la carpeta world
volumes:
  world-data:
