services:
  minecraft-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-server
    ports:
      - "0.0.0.0:25565:25565"
    stdin_open: true # habilita entrada STDIN
    logging:
      driver: json-file # Solo esto ya mejora el formato de logs
    tty: true # habilita pseudo-TTY para logs
    restart: unless-stopped
    volumes:
      - world-data:/minecraft/world
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN} # Reemplaza con tu token de bot de Discord
      - DISCORD_CHANNEL_GLOBAL=${DISCORD_CHANNEL_GLOBAL} # Reemplaza con tu ID
      - DISCORD_CHANNEL_LOG=${DISCORD_CHANNEL_LOG} # Reemplaza con tu ID
# Volumen para persistir la carpeta world
volumes:
  world-data:
