services:
  minecraft-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-server
    ports:
      - "0.0.0.0:25565:25565/tcp"
      - "0.0.0.0:2222:22/tcp"
    stdin_open: true # habilita entrada STDIN
    tty: true # habilita pseudo-TTY para logs
    volumes:
      - world-data:/minecraft/world

volumes:
  world-data:
