services:
  minecraft-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-server
    ports:
      - "0.0.0.0:25565:25565/tcp"
    stdin_open: true # habilita entrada STDIN
    tty: true # habilita pseudo-TTY para logs
    volumes:
      - creativo-data:/minecraft/creativo
      - world-data:/minecraft/world
      - discordsrv-config:/minecraft/plugins/DiscordSRV
      - login-config:/minecraft/plugins/nLogin
      - luckperms:/minecraft/plugins/LuckPerms

volumes:
  creativo-data:
  world-data:
  discordsrv-config:
  login-config:
  luckperms:
